// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

/** Avoid broken shadow connections when .env has trailing CRLF/spaces (common on Windows). */
const envTrim = (name: string) => env(name).trim();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envTrim("DIRECT_URL"),
    shadowDatabaseUrl: envTrim("SHADOW_DATABASE_URL"),
  },
});
