// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

dotenv.config({ path: [".env.local", ".env"] });

/** Avoid broken shadow connections when .env has trailing CRLF/spaces (common on Windows). */
const envTrim = (name: string) => env(name).trim();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envTrim("POSTGRES_URL"),
  },
});
